services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: azeumo-app:latest
    container_name: azeumo-app
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.azeumo.rule=Host(`azeumo.cloud.anuvis.net`)"
      - "traefik.http.routers.azeumo.entrypoints=websecure"
      - "traefik.http.routers.azeumo.tls.certresolver=letsencrypt"
      - "traefik.http.services.azeumo.loadbalancer.server.port=80"
    environment:
      APP_NAME: Azeumo
      APP_ENV: production
      APP_DEBUG: "false"
      APP_URL: https://azeumo.cloud.anuvis.net
      APP_KEY: base64:tdKXITVU+WrQLbQhQsiWYeN8FivkDW47yFGL7KPsot4=
      APP_LOCALE: fr
      APP_FALLBACK_LOCALE: en
      DB_CONNECTION: mysql
      DB_HOST: 172.25.0.1
      DB_PORT: 3306
      DB_DATABASE: azeumo
      DB_USERNAME: azeumo
      DB_PASSWORD: azeumo2026!
      SESSION_DRIVER: database
      SESSION_SECURE_COOKIE: "true"
      SESSION_DOMAIN: azeumo.cloud.anuvis.net
      CACHE_STORE: database
      QUEUE_CONNECTION: sync
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
